### ISSUE TITLE
Raise SMTPServerDisconnected

### ISSUE THREAD

**Issue by Arinze1020** [aahnik/AutoMailer#10]
raise

```
SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected:Connection unexpectedly closed.
```

I have tried changing the port and using SMTP_SSL but non seems to work

**Comment by aahnik** [comment]
This is a problem while connecting with the server. Check if your password and email id are correct. There may be many other reasons.
